<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { CopyStatus } from '$lib/types/book.type';

  export let bookId: number;
  export let bookTitle: string = '';

  const dispatch = createEventDispatcher();

  // Form data
  let quantity = 1;
  let call_number = '';
  let status: CopyStatus = 'available';
  let acquisition_date = new Date().toISOString().split('T')[0];
  let notes = '';

  let isSubmitting = false;
  let error = '';

  const statusOptions: { value: CopyStatus; label: string }[] = [
    { value: 'available' as CopyStatus, label: 'Available' },
    { value: 'borrowed' as CopyStatus, label: 'Borrowed' },
    { value: 'maintenance' as CopyStatus, label: 'Maintenance' },
    { value: 'lost' as CopyStatus, label: 'Lost' },
    { value: 'damaged' as CopyStatus, label: 'Damaged' }
  ];

  function validateForm(): boolean {
    error = '';

    if (quantity < 1) {
      error = 'Quantity must be at least 1';
      return false;
    }

    if (quantity > 100) {
      error = 'Quantity cannot exceed 100';
      return false;
    }

    return true;
  }

  async function handleSubmit() {
    if (!validateForm()) return;

    isSubmitting = true;
    try {
      // FIXED: Send flat structure matching backend DTO
      dispatch('submit', {
        book_id: bookId,  // Changed from bookId to book_id
        quantity,
        call_number: call_number || undefined,
        status,
        acquisition_date: acquisition_date || undefined,  // Keep as ISO string
        notes: notes || undefined
      });
    } finally {
      isSubmitting = false;
    }
  }

  function handleCancel() {
    dispatch('cancel');
  }

  function increment() {
    if (quantity < 100) {
      quantity++;
    }
  }

  function decrement() {
    if (quantity > 1) {
      quantity--;
    }
  }
</script>

<div class="bg-white rounded-lg shadow-sm">
  <div class="p-6 border-b border-gray-200">
    <h2 class="text-2xl font-bold text-gray-900">Add Book Copies</h2>
    {#if bookTitle}
      <p class="text-gray-600 mt-1">Adding copies for: <span class="font-semibold">{bookTitle}</span></p>
    {/if}
  </div>

  <form on:submit|preventDefault={handleSubmit} class="p-6 space-y-6">
    <!-- Info Box -->
    <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
      <div class="flex items-start gap-3">
        <svg class="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div class="text-sm text-blue-800">
          <p class="font-semibold mb-1">Barcode Generation</p>
          <p>Barcodes will be automatically generated by the system for each copy. The settings below will apply to ALL copies created.</p>
        </div>
      </div>
    </div>

    <!-- Quantity Selector -->
    <div>
      <label for="quantity" class="block text-sm font-semibold text-gray-700 mb-2">
        Number of Copies <span class="text-red-500">*</span>
      </label>
      
      <div class="flex items-center gap-4">
        <!-- Decrement Button -->
        <button
          type="button"
          on:click={decrement}
          disabled={quantity <= 1 || isSubmitting}
          class="w-12 h-12 flex items-center justify-center bg-gray-100 hover:bg-gray-200 rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H4" />
          </svg>
        </button>

        <!-- Quantity Display -->
        <div class="flex-1 max-w-xs">
          <input
            type="number"
            id="quantity"
            bind:value={quantity}
            min="1"
            max="100"
            class="w-full px-4 py-3 text-center text-2xl font-bold border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
            disabled={isSubmitting}
          />
        </div>

        <!-- Increment Button -->
        <button
          type="button"
          on:click={increment}
          disabled={quantity >= 100 || isSubmitting}
          class="w-12 h-12 flex items-center justify-center bg-gray-100 hover:bg-gray-200 rounded-lg transition disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
        </button>
      </div>

      <p class="text-sm text-gray-500 mt-2">Maximum: 100 copies per request</p>

      {#if error}
        <p class="mt-2 text-sm text-red-600">{error}</p>
      {/if}
    </div>

    <!-- Quick Quantity Buttons -->
    <div class="space-y-2">
      <p class="text-sm font-semibold text-gray-700">Quick Select:</p>
      <div class="flex gap-2 flex-wrap">
        {#each [1, 5, 10, 20, 50] as quickQuantity}
          <button
            type="button"
            on:click={() => quantity = quickQuantity}
            disabled={isSubmitting}
            class={`px-4 py-2 rounded-lg font-medium text-sm transition ${
              quantity === quickQuantity
                ? 'bg-orange-500 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            } disabled:opacity-50 disabled:cursor-not-allowed`}
          >
            {quickQuantity}
          </button>
        {/each}
      </div>
    </div>

    <!-- Divider -->
    <hr class="border-gray-200" />

    <!-- Optional Fields Section -->
    <div class="space-y-4">
      <h3 class="text-lg font-semibold text-gray-900">Copy Details (Optional)</h3>
      <p class="text-sm text-gray-600">These settings will apply to ALL {quantity} {quantity === 1 ? 'copy' : 'copies'}</p>

      <!-- Call Number -->
      <div>
        <label for="call_number" class="block text-sm font-semibold text-gray-700 mb-2">
          Call Number
        </label>
        <input
          type="text"
          id="call_number"
          bind:value={call_number}
          placeholder="e.g., 005.1 MAR"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
          disabled={isSubmitting}
        />
        <p class="text-xs text-gray-500 mt-1">Library classification number</p>
      </div>

      <!-- Status -->
      <div>
        <label for="status" class="block text-sm font-semibold text-gray-700 mb-2">
          Status
        </label>
        <select
          id="status"
          bind:value={status}
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
          disabled={isSubmitting}
        >
          {#each statusOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
      </div>

      <!-- Acquisition Date -->
      <div>
        <label for="acquisition_date" class="block text-sm font-semibold text-gray-700 mb-2">
          Acquisition Date
        </label>
        <input
          type="date"
          id="acquisition_date"
          bind:value={acquisition_date}
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
          disabled={isSubmitting}
        />
      </div>

      <!-- Notes -->
      <div>
        <label for="notes" class="block text-sm font-semibold text-gray-700 mb-2">
          Notes
        </label>
        <textarea
          id="notes"
          bind:value={notes}
          rows="3"
          placeholder="Add any notes about these copies..."
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-500"
          disabled={isSubmitting}
        />
      </div>
    </div>

    <!-- Preview -->
    <div class="bg-gray-50 border border-gray-200 rounded-lg p-4">
      <p class="text-sm font-semibold text-gray-700 mb-2">Preview:</p>
      <div class="space-y-1">
        <p class="text-sm text-gray-600">
          📚 <span class="font-semibold">{quantity}</span> {quantity === 1 ? 'copy' : 'copies'} will be created
        </p>
        <p class="text-sm text-gray-600">
          🏷️ Barcodes: Auto-generated (e.g., LBTS-2026-00001, LBTS-2026-00002...)
        </p>
        <p class="text-sm text-gray-600">
          📊 Status: <span class="font-semibold">{status}</span>
        </p>
        {#if call_number}
          <p class="text-sm text-gray-600">
            📖 Call Number: <span class="font-semibold">{call_number}</span>
          </p>
        {/if}
        {#if notes}
          <p class="text-sm text-gray-600">
            📝 Notes: <span class="font-semibold">{notes}</span>
          </p>
        {/if}
      </div>
    </div>

    <!-- Actions -->
    <div class="flex gap-3 pt-4">
      <button
        type="submit"
        disabled={isSubmitting}
        class="flex-1 bg-gradient-to-r from-orange-500 to-orange-600 text-white py-3 rounded-lg font-semibold hover:from-orange-600 hover:to-orange-700 transition disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {isSubmitting ? 'Creating Copies...' : `Create ${quantity} ${quantity === 1 ? 'Copy' : 'Copies'}`}
      </button>
      <button
        type="button"
        on:click={handleCancel}
        disabled={isSubmitting}
        class="px-6 py-3 border border-gray-300 rounded-lg font-semibold text-gray-700 hover:bg-gray-50 transition disabled:opacity-50 disabled:cursor-not-allowed"
      >
        Cancel
      </button>
    </div>
  </form>
</div>